set dotenv-load
set dotenv-path := "../../.env"

release := "system"

cert-manager:
    helm repo add jetstack https://charts.jetstack.io
    helm repo update
    helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version 1.17.2 --set crds.enabled=true

ingress:
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo update
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --version 4.12.3 

install: cert-manager ingress
    helm upgrade --install {{release}} . --create-namespace --namespace {{release}} \
    --set letsencrypt.email="$LETSENCRYPT_EMAIL" 
setns:
    kubectl config set-context --current --namespace={{release}}