set positional-arguments

update-dependencies:
    helm dependency update
    
install:
    safehelm install {{release}} . --create-namespace --namespace {{namespace}}

upgrade:
    safehelm upgrade {{release}} . --namespace {{namespace}}

setns:
    kubectl config set-context --current --namespace={{namespace}}

sops-lock file:
    # Use this to lock a new values file in place
    sops -e -i $1