apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}