{{- $dbHost := printf "%s-pg-rw.%s.svc.cluster.local" .Release.Name .Release.Namespace }}

apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-server-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  NC_DB: {{ (printf "pg://%s:5432?u=%s&p=%s&d=%s" $dbHost .Values.postgres.username .Values.postgres.password .Values.postgres.dbname) | b64enc }}
