apiVersion: v1
kind: Service
metadata:
  name: nocodb-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nocodb-{{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: nocodb-{{ .Release.Name }}